### ISSUE TITLE
pushurl support needed

### ISSUE THREAD

**Issue by tiberiuichim** [collective/mrs-developer#11]
It would be nice to have support to specify a pushurl, similar to how mr.developer supports it.

**Comment by avoinea** [comment]
I think this can be easily tackled with `--https` option.

**Comment by pnicolli** [comment]
I took some time to look into this. Apparently we would need to upgrade ``simple-git`` to version 2 in order to benefit from the possibility to add options to ``addRemote``. I will see if I can write a PR for this, a quick test show that some tests fail when upgrading.
